apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: datn2026-stt43
type: Opaque
stringData:
  MongoDb__ConnectionString: "${MONGODB_CONNECTION_STRING}"
  Oauth2__Google__ClientId: "${OAUTH2_GOOGLE_CLIENT_ID}"
  Oauth2__Google__ClientSecret: "${OAUTH2_GOOGLE_CLIENT_SECRET}"
  Smtp__Password: "${SMTP_PASSWORD}"
  Smtp__Username: "${SMTP_USERNAME}"
  Secret__GmailNotification: "${SMTP_PASSWORD}"
  RabbitMQ__UserName: "${RABBITMQ_USERNAME}"
  RabbitMQ__Password: "${RABBITMQ_PASSWORD}"
  Key__SecretKey: "${JWT_SECRET_KEY}"
  CloudflareR2__AccessKey: "${CLOUDFLARE_R2_ACCESS_KEY}"
  CloudflareR2__SecretKey: "${CLOUDFLARE_R2_SECRET_KEY}"
  CloudflareR2__Endpoint: "${CLOUDFLARE_R2_ENDPOINT}"
  CloudflareR2__BucketName: "${CLOUDFLARE_R2_BUCKET_NAME}"
  CloudflareR2__PublicBaseUrl: "${CLOUDFLARE_R2_PUBLIC_BASE_URL}"
